### ISSUE TITLE
Google translate not working

### ISSUE THREAD

**Issue by BruceLee569** [FilipePS/Traduzir-paginas-web#409]
When I translate full page using google engine, an error is as follows:
```
pageTranslator.js:479 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at translateAttributes (pageTranslator.js:479:56)
    at pageTranslator.js:565:37
```
After modify engine to Yandex, it works again.

**Comment by FilipePS** [comment]
Since you are probably from Mainland China and Google Translate has been blocked in most parts of Mainland China, please use Bing as your translation service.
